version: '3.8'

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile.go
    ports:
      - "8080:8080"
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_secrets_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_secrets_password
      POSTGRES_DB_FILE: /run/secrets/db_secrets_database
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_secrets_username
      POSTGRES_PASSWORD_FILE: /run/secrets/db_secrets_password
      POSTGRES_DB_FILE: /run/secrets/db_secrets_database
    ports:
      - "5432:5432"
    secrets:
      - db_secrets_username
      - db_secrets_password
      - db_secrets_database

secrets:
  db_secrets_username:
    external: true
  db_secrets_password:
    external: true
  db_secrets_database:
    external: true
